### ISSUE TITLE
Migrate to the new official Cassandra Ruby Driver

### ISSUE THREAD

**Issue by elado** [cequel/cequel#153]
Cql-rb is discontinued, and development moved to https://github.com/datastax/ruby-driver

**Comment by victorborda** [comment]
Looking to use cequel on a project - curious if the datastax driver integration branch is ready for merging into master or is further work needed? Might be able to help out although I am just getting familiar with Cassandra...

**Comment by joerocklin** [comment]
After merging current master into https://github.com/outoftime/cequel/tree/datastax_cassandra_driver, all tests pass with Rails 4.2 and Ruby 2.1.5/2.2.0 (with the exception of the pending drop_column test). Is a merge waiting on something else? (I'm also relatively new to Cassandra, so won't be surprised if I'm missing something obvious).

**Comment by outoftime** [comment]
@joerocklin what Cassandra version are you running the specs against? have you tried running them a few times? i am getting nondeterministic, fairly inexplicable intermittent failures in the `data_set_spec`

**Comment by joerocklin** [comment]
@outoftime Ooops, I guess that would help, wouldn't it: I was running against 2.1.2 (via the included vagrantfile). I ran through the tests twice: once on Ruby 2.1.5 and once with 2.2.0 with consistent results. Though 2 data points obviously do not make a trend.

**Comment by outoftime** [comment]
Released 1.6.0 with the DataStax driver!

**Comment by joerocklin** [comment]
@outoftime Awesome! I'm curious what the final issue was with the nondeterministic tests. I had run a bunch of them and saw the behavior as well but never got around to delving into the issue.

**Comment by outoftime** [comment]
@joerocklin I was running the tests against my OSX install of Cassandra 2.1.2, which is not a production-ready version using the heuristic of inclusion in DSE. I was seeing some other weird intermittent failures on other branches as well. Dropped back to 2.0.12 (which I should've been using all along) and all looks good.

**Comment by victorborda** [comment]
Awesome! :+1:  Thank you @outoftime
