### ISSUE TITLE
Error running with Rails 4.2.0beta4

### ISSUE THREAD

**Issue by zshenker** [cequel/cequel#193]
I receive the following error when trying to use cequel with Rails 4.2.0beta4:

/usr/local/lib/ruby/2.1.0/forwardable.rb:132:in `instance_delegate': wrong number of arguments (2 for 1) (ArgumentError)
	from /usr/local/bundle/gems/activemodel-4.2.0.beta4/lib/active_model/naming.rb:219:in `extended'
	from /usr/local/bundle/gems/activemodel-4.2.0.beta4/lib/active_model/validations.rb:42:in `extend'
	from /usr/local/bundle/gems/activemodel-4.2.0.beta4/lib/active_model/validations.rb:42:in `block in <module:Validations>'
	from /usr/local/bundle/gems/activesupport-4.2.0.beta4/lib/active_support/concern.rb:120:in `class_eval'
	from /usr/local/bundle/gems/activesupport-4.2.0.beta4/lib/active_support/concern.rb:120:in `append_features'
	from /usr/local/bundle/gems/cequel-1.4.5/lib/cequel/record/validations.rb:27:in `include'
	from /usr/local/bundle/gems/cequel-1.4.5/lib/cequel/record/validations.rb:27:in `block in <module:Validations>'
	from /usr/local/bundle/gems/activesupport-4.2.0.beta4/lib/active_support/concern.rb:120:in `class_eval'
	from /usr/local/bundle/gems/activesupport-4.2.0.beta4/lib/active_support/concern.rb:120:in `append_features'
	from /usr/local/bundle/gems/cequel-1.4.5/lib/cequel/record.rb:92:in `include'
	from /usr/local/bundle/gems/cequel-1.4.5/lib/cequel/record.rb:92:in `block in <module:Record>'
	from /usr/local/bundle/gems/activesupport-4.2.0.beta4/lib/active_support/concern.rb:120:in `class_eval'
	from /usr/local/bundle/gems/activesupport-4.2.0.beta4/lib/active_support/concern.rb:120:in `append_features'
	from /usr/src/app/app/models/asset.rb:3:in `include'
	from /usr/src/app/app/models/asset.rb:3:in `<class:Asset>'
	from /usr/src/app/app/models/asset.rb:1:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-4.2.0.beta4/lib/active_support/dependencies.rb:452:in `load'
	from /usr/local/bundle/gems/activesupport-4.2.0.beta4/lib/active_support/dependencies.rb:452:in `block in load_file'
	from /usr/local/bundle/gems/activesupport-4.2.0.beta4/lib/active_support/dependencies.rb:642:in `new_constants_in'
	from /usr/local/bundle/gems/activesupport-4.2.0.beta4/lib/active_support/dependencies.rb:451:in `load_file'
	from /usr/local/bundle/gems/activesupport-4.2.0.beta4/lib/active_support/dependencies.rb:349:in `require_or_load'
	from /usr/local/bundle/gems/activesupport-4.2.0.beta4/lib/active_support/dependencies.rb:489:in `load_missing_constant'
	from /usr/local/bundle/gems/activesupport-4.2.0.beta4/lib/active_support/dependencies.rb:184:in `const_missing'
	from /usr/src/app/spec/factories.rb:10:in `block in <top (required)>'
	from /usr/local/bundle/gems/factory_girl-4.5.0/lib/factory_girl/syntax/default.rb:49:in `instance_eval'
	from /usr/local/bundle/gems/factory_girl-4.5.0/lib/factory_girl/syntax/default.rb:49:in `run'
	from /usr/local/bundle/gems/factory_girl-4.5.0/lib/factory_girl/syntax/default.rb:7:in `define'
	from /usr/src/app/spec/factories.rb:1:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-4.2.0.beta4/lib/active_support/dependencies.rb:246:in `load'
	from /usr/local/bundle/gems/activesupport-4.2.0.beta4/lib/active_support/dependencies.rb:246:in `block in load'
	from /usr/local/bundle/gems/activesupport-4.2.0.beta4/lib/active_support/dependencies.rb:237:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-4.2.0.beta4/lib/active_support/dependencies.rb:246:in `load'
	from /usr/local/bundle/gems/factory_girl-4.5.0/lib/factory_girl/find_definitions.rb:16:in `block in find_definitions'
	from /usr/local/bundle/gems/factory_girl-4.5.0/lib/factory_girl/find_definitions.rb:15:in `each'
	from /usr/local/bundle/gems/factory_girl-4.5.0/lib/factory_girl/find_definitions.rb:15:in `find_definitions'
	from /usr/local/bundle/gems/factory_girl_rails-4.5.0/lib/factory_girl_rails/railtie.rb:21:in `block in <class:Railtie>'
	from /usr/local/bundle/gems/activesupport-4.2.0.beta4/lib/active_support/lazy_load_hooks.rb:36:in `call'
	from /usr/local/bundle/gems/activesupport-4.2.0.beta4/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
	from /usr/local/bundle/gems/activesupport-4.2.0.beta4/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
	from /usr/local/bundle/gems/activesupport-4.2.0.beta4/lib/active_support/lazy_load_hooks.rb:44:in `each'
	from /usr/local/bundle/gems/activesupport-4.2.0.beta4/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
	from /usr/local/bundle/gems/railties-4.2.0.beta4/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
	from /usr/local/bundle/gems/railties-4.2.0.beta4/lib/rails/initializable.rb:30:in `instance_exec'
	from /usr/local/bundle/gems/railties-4.2.0.beta4/lib/rails/initializable.rb:30:in `run'
	from /usr/local/bundle/gems/railties-4.2.0.beta4/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/local/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
	from /usr/local/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /usr/local/lib/ruby/2.1.0/tsort.rb:345:in `each'
	from /usr/local/lib/ruby/2.1.0/tsort.rb:345:in `call'
	from /usr/local/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
	from /usr/local/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
	from /usr/local/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
	from /usr/local/bundle/gems/railties-4.2.0.beta4/lib/rails/initializable.rb:54:in `run_initializers'
	from /usr/local/bundle/gems/railties-4.2.0.beta4/lib/rails/application.rb:349:in `initialize!'
	from /usr/src/app/config/environment.rb:5:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-4.2.0.beta4/lib/active_support/dependencies.rb:252:in `require'
	from /usr/local/bundle/gems/activesupport-4.2.0.beta4/lib/active_support/dependencies.rb:252:in `block in require'
	from /usr/local/bundle/gems/activesupport-4.2.0.beta4/lib/active_support/dependencies.rb:237:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-4.2.0.beta4/lib/active_support/dependencies.rb:252:in `require'
	from /usr/local/bundle/gems/spring-1.1.3/lib/spring/application.rb:92:in `preload'
	from /usr/local/bundle/gems/spring-1.1.3/lib/spring/application.rb:140:in `serve'
	from /usr/local/bundle/gems/spring-1.1.3/lib/spring/application.rb:128:in `block in run'
	from /usr/local/bundle/gems/spring-1.1.3/lib/spring/application.rb:122:in `loop'
	from /usr/local/bundle/gems/spring-1.1.3/lib/spring/application.rb:122:in `run'
	from /usr/local/bundle/gems/spring-1.1.3/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'

**Comment by johnrees** [comment]
:+1: just ran into this on 4.2 final

**Comment by Sixeight** [comment]
I think this issue is insert into Rails at this commit:  https://github.com/rails/rails/commit/10adc2ee90c34003edb5850b63c6cae321c09008

Try following patch as first-aid:

```ruby
module Forwardable
  remove_method :delegate
end
```

**Comment by johnrees** [comment]
Yes, that seems to fixed things for now. Thanks

**Comment by islue** [comment]
So, any plan to fix the issue on cequel side?

**Comment by olance** [comment]
+1

**Comment by olance** [comment]
@Sixeight where would you put that patch? I tried in an initializer as suggested in #211 but without success :/

**Comment by Sixeight** [comment]
@olance I recommend to put patch in `config/initializer/forwardable.rb`. but you weren't success...
umm... try to put patch before `Bundler.require(*Rails.groups)` at `config/application.rb` .

I'm sorry, I'm not good at English X(

**Comment by olance** [comment]
It's quite good enough, thanks! :+1: 

It does "work" now but just because Cequel doesn't use the `delegate` method itself. My project uses Prawn which makes use of `delegate` and it's now trying to call the ActiveSupport one. Nightmare!

**Comment by Sixeight** [comment]
@olance wow, sounds like a lot of bother :scream_cat: 
I created PR with tiny hack around `delegate`. Try this hack for your project.

**Comment by Micka33** [comment]
Just ran into this error. @Sixeight's patch fixed it.
I created an initializer `monkey_patch.rb` for it.
```ruby
# See : https://github.com/cequel/cequel/issues/193
# wrong number of arguments (2 for 1)
# /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/forwardable.rb:132:in `instance_delegate'
module Forwardable
  remove_method :delegate
end
```

This error occurs when launching Sidekiq.
```
cequel (1.5.0)
sidekiq (3.3.1)
rails (4.2.0)
activejob (= 4.2.0)
activemodel (= 4.2.0)
activerecord (= 4.2.0)
activesupport (= 4.2.0)
```

Is this patch good enough for production ?
Is it good enough for a PR ?
Hope to see it fixed soon.

**Comment by Micka33** [comment]
@olance I'm talking about the PR, see: https://github.com/Sixeight/cequel/commit/d063ef15b6bae07253205e927c2d52682cd8a8d5

@Sixeight fix the error by creating/requiring a custom `cequel/forwardable`.

**Comment by olance** [comment]
oh, so sorry, I read a bit too quickly and hadn't seen the PR :/

It indeed looks like a much better fix!
I'll see if I can test it here.
