### ISSUE TITLE
Use the official cassandra driver

### ISSUE THREAD

**Issue by teodor-pripoae** [cequel/cequel#217]
Hi,

I created a patch for `cql-rb` for running under ruby `2.0.0` and it was rejected saying that `cql-rb` is no longer supported, and that `cequel` should use the official [datastax/ruby-driver](https://github.com/datastax/ruby-driver) driver.

https://github.com/iconara/cql-rb/pull/125

I don't have a minimal code to reproduce the issue, but basically starting from ruby `2.2.0` if you sort objects by `Cql::TimeUuid` class (`key` or `foreign_key`) and some of this objects are nil, it will raise some warnings:

```
../gems/cequel-1.5.0/lib/cequel/record/dirty.rb:59: warning: Comparable#== will no more rescue exceptions of #<=> in the next release.
../gems/cequel-1.5.0/lib/cequel/record/dirty.rb:59: warning: Return nil in #<=> if the comparison is inappropriate or avoid such comparison.
```

Starting from ruby `2.3` I believe this will transform automatically in errors.

**Comment by rtatavarty** [comment]
An issue #153 is already created for the same. And a private branch with some progress is at @outoftime /cequel. Not sure of the ETA. May be this can be duped.

**Comment by outoftime** [comment]
FYI all—[the private branch](https://github.com/outoftime/cequel/tree/datastax_cassandra_driver) is in pretty good shape, but a few specs in the `data_set_spec` that fail nondeterministically for reasons that aren't clear but might be a bug in the CQL driver. I'm hoping to put together a reduction fairly soon to confirm that it's a driver issue, but that's what's blocking it right now.

If anyone else who's highly motivated wants to take a look at that branch / the spec failures, that certainly wouldn't be unwelcome ; )
