### ISSUE TITLE
Need help creating a compound partition key

### ISSUE THREAD

**Issue by johnrees** [cequel/cequel#219]
I want to do this
```
CREATE TABLE pushes (
  owner_id int,
  push_month int,
  pushed_at timestamp,
  values map<text, text>,
  PRIMARY KEY ((owner_id, push_month), pushed_at)
) WITH CLUSTERING ORDER BY (pushed_at DESC);
```

but am having issues creating the compound partition key `(owner_id, push_month)`, here's what I have- currently only `owner_id` is the partition key. I don't want to use `belongs_to` because `Owner` is actually a postgres ActiveRecord model.

```
class Push
  include Cequel::Record
  key :owner_id, :int
  key :push_month, :int
  key :pushed_at, :timestamp, order: :desc, index: true
  map :values, :text, :text
...
```

Can anyone help? Thanks

**Comment by outoftime** [comment]
By default only the first `key` is added to the partition key, but you can override this behavior with the `:partition` option:

```ruby
key :owner_id, :int
  key :push_month, :int, partition: true
  key :pushed_at, :timestamp, order: :desc, index: true
  map :values, :text, :text
```

Feel free to reopen if that doesn't clear things up!
