### ISSUE TITLE
How to delete many rows

### ISSUE THREAD

**Issue by Micka33** [cequel/cequel#237]
I want to generate this query with Cequel:

```cql
DELETE FROM users where pk = 'jsmith' and cc < 100;
```

Let's say my user model looks like this
```
ruby
class Users
    include Cequel::Record

    key :pk, :bigint, { partition: true } # partition key
    key :cc, :timestamp, { order: :desc } # clustering column

end
```

Right now, I am iterating through the rows using a simple where clause and destroy them one by one.
How can I use my `Users` model to generate the above CQL statement.

EDIT: Also posted on [stackoverflow](http://stackoverflow.com/questions/30104089/how-to-generate-a-delete-statement-with-cequel-rails)

**Comment by outoftime** [comment]
@Micka33 have you tried:

```ruby
Users.where(pk: 'jsmith').upto(100).delete_all
```

Although I think that will still perform a `SELECT` followed by a series of `DELETE WHERE…IN` statements—I don't think Cassandra has always supported the `DELETE` approach you have above, does that definitely work now?

**Comment by Micka33** [comment]
@outoftime 

Actually trying on `Cassandra 2.1.2` with `CQL 3.2.0`.  
You are are right about the `smaller-than` part, it is not allowed to use it on a primary key part in a `DELETE` statement.

```cql
 ~ cqlsh
Connected to Test Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 2.1.2 | CQL spec 3.2.0 | Native protocol v3]
Use HELP for help.
cqlsh:db_development> DELETE FROM users WHERE pk = 'jsmith' AND cc < 100 ;
code=2200 [Invalid query] message="Invalid operator < for PRIMARY KEY part cc"
cqlsh:db_development> DELETE FROM users WHERE pk = 'jsmith' AND cc = 100 ;
cqlsh:db_development>
```

Thank you for pointing me to the `delete_all` method.
```ruby
irb(main):036:0> Users.where(pk: 'jsmith').where(cc: 100).delete_all
CQL (2ms) DELETE FROM users WHERE pk = 'jsmith' AND cc = 100
=> #<Cassandra::Result:0x3fdb891da8cc @rows=[] @last_page=true>
irb(main):037:0>
```

As I have more clustering columns after the `cc` one, iterating through the `cc`s gives me a more effective solution than iterating through each of the other clustering columns under cc.
