### ISSUE TITLE
get max value of a spesific column

### ISSUE THREAD

**Issue by yeudit** [cequel/cequel#259]
I'm trying to get the max value of a column type integer:
Person.all.max_by{|p|p.num}
and the query that runing behind is:
select (*) from persons;

I want to run something like: 
select max(num) from persons;
for improving performance

how can I do it?

**Comment by outoftime** [comment]
@yeudit Cassandra doesn’t support SQL aggregate functions like `MAX` (with the exception of `COUNT`, which actually *does* iterate over every row internally if I recall).

One thing you could do is store a secondary representation with a clustering column of `num` and a data column like `person_id`. However it’s not clear how you would construct your partition key.
