### ISSUE TITLE
seed the time portion of timeuuid

### ISSUE THREAD

**Issue by rossi-jeff** [cequel/cequel#273]
I have a rails app with data in mysql I would like to archive and was considering using cequel and cassandra. Since the records I am wishing to archive have created_at values in the past I would like to use reading.created_at to seed the time portion of the timeuuid, so that when querying it would find values in the time range the user is looking for. Is this possible?

**Comment by pezra** [comment]
If the `created_at` column is a key column, cequel would certainly allow you to query on that column. This is a Cassandra data modeling question, really. Cequel will execute any queries acceptable to Cassandra. It is worth noting, though, that it is almost certainly a very bad idea to make `created_at` a partition key. It would likely be better to make the partition key some portion of the time stamp, such as the year, and the to have the timestamp itself be a cluster key.
