### ISSUE TITLE
Readme recommends deprecated #[] instead of #values_at

### ISSUE THREAD

**Issue by tloudon** [cequel/cequel#275]
Just got:
>Calling #[] with multiple arguments is deprecated. Use #values_at

and noticed https://github.com/cequel/cequel/blob/6731076b24825eda212912b9c37c56a6d7ea6976/lib/cequel/record/record_set.rb#L271

Any reason to hold off on updating the [Readme](https://github.com/cequel/cequel/blob/master/README.md#record-sets) here?  Happy to submit a PR.

Thanks!

> You can pass multiple arguments to the [] operator, which will generate an IN query:
`
Post['bigdata', 'nosql'] # scopes posts with blog_subdomain IN ("bigdata", "nosql")`

**Comment by pezra** [comment]
No reason at all. Please do.
