### ISSUE TITLE
Cequel with Jruby 1.7.16

### ISSUE THREAD

**Issue by Trehana** [cequel/cequel#286]
I am trying to install cequel with rbenv version jruby 1.7.16 but it gives an error saying "Fetching: cequel-1.7.0.gem (100%)
ERROR:  Error installing cequel:
	cequel requires Ruby version >= 2.0.". I am new to cequel please help me to figure it out.
Thanks in advance.

**Comment by pezra** [comment]
I believe jruby 1.7.16 is not ruby 2.1 compatible. Unfortunately, Cequel requires ruby 2.1 to operate correctly.
