### ISSUE TITLE
Support of cassandra 3.x

### ISSUE THREAD

**Issue by demonodojo** [cequel/cequel#298]
I really appreciate that cequel could use the new cassandra-driver 3.x

**Comment by erkie** [comment]
What is the status of this project? Is it alive? Are major things like this being looked at?

**Comment by pezra** [comment]
The project is alive and well. We would love to have c* 3 support. I would
merge a PR providing that functionality.

**Comment by hugowschneider** [comment]
With the incoming release of DSE 5.0, this feature would be really nice together with C*3 static columns and materialised views!

**Comment by yoonwaiyan** [comment]
Would love to see this too as Cassandra 2.x is ending their support on December this year and I'm using Cassandra 3.5 now. Currently I have execute all queries in raw CQL using official driver.

**Comment by pezra** [comment]
C* 3.x support is coming in PR #316

**Comment by pezra** [comment]
#324 is merged. The next release will support C* 3.x.

**Comment by pezra** [comment]
Cassandra 3.x is supported by version 2.0.
