### ISSUE TITLE
How to customize Table name in Cequel?

### ISSUE THREAD

**Issue by rtatavarty** [cequel/cequel#305]
For a Cequel record/schema, the name is generated by rake cequel:migrate. But how do we assign a name in the model definition?

I tried the following but it did not work (Cequel 1.7.0):

```
class MyInfo
  include Cequel::Record

  key :name, :text
  column :info, :text

  self.table_name = "my_info_2" #<<< need to set a custom name

end
```
Note: Also posted on SO - not sure which place is appropriate for a question like this.

**Comment by pezra** [comment]
The ` self.table_name = ...` syntax works for the current version (1.9.1). A lot of improvements have been made in the 9 months since 1.7.0 was released. Any chance you could upgrade?

**Comment by rtatavarty** [comment]
Sure, will upgrade to the latest stable. Thanks!
