### ISSUE TITLE
Don't support Rails 5?

### ISSUE THREAD

**Issue by saharaying** [cequel/cequel#310]

**Comment by pezra** [comment]
Cequel has not been tested with Rails 5. We would happily accept a PR that corrected any incompatibilities and updated the readme.

**Comment by emn178** [comment]
Hi, 

I made a PR #315 to support this.
Before it merged, you could use my fork https://github.com/emn178/cequel

**Comment by pungoyal** [comment]
@emn178 your version doesn't seem to support cassandra 3. I get:

`Cassandra::Errors::InvalidError: unconfigured table schema_keyspaces`

**Comment by emn178** [comment]
@pungoyal it seems not to support Cassandra 3. see https://github.com/cequel/cequel#compatibility

**Comment by pezra** [comment]
Rails 5 support was added in version 2.0.
