### ISSUE TITLE
Is the rubydoc wrong about the default value of :consistency?

### ISSUE THREAD

**Issue by hydrogen18** [cequel/cequel#334]
There are many methods that document a default value of `consistency`. For example, from `persistence.rb`

```
      # Remove this record from the database
      #
      # @param options [Options] options for deletion
      # @option options [Symbol] :consistency (:quorum) what consistency with
      #   which to persist the deletion
      # @option options [Time] :timestamp the writetime to use for the deletion
      #
      # @return [Record] self
      #
      def destroy(options = {})
        options.assert_valid_keys(:consistency, :timestamp)
        assert_keys_present!
        metal_scope.delete(options)
        transient!
        self
      end
```

This seems to indicate a default value of `:quorum` for consistency. A while back the cassandra driver gem changed from a default of quorom to "local_one". I don't understand the difference exactly, but did that change make all this rubydoc obsolete?

Should we just consider removing the default and instead document that the default consistency is whatever is specified by the cassandra driver gem?

**Comment by pezra** [comment]
I think the change you suggest is a good one. There is a substantial difference between `quorum` and `local_one`. It would be really unfortunate for a client to believe the wrong one was the default.

**Comment by hydrogen18** [comment]
I will open an MR to remove the listing of the default values of `:consistency` and add somewhere to indicate how consistency is configured and where.
