### ISSUE TITLE
Support for multiple keyspace connection?

### ISSUE THREAD

**Issue by rootcss** [cequel/cequel#338]
Hi Guys, 
Does cequel support connection to multiple keyspaces?
Eg, one of the models connects to keyspace1, while other connects to keyspace2.
I have been trying to do, but not able to figure it out, as the new connection overrides the previous one.
Thanks in Advance!

**Comment by rootcss** [comment]
@outoftime @pezra Guys, any suggestions on this.

**Comment by bernardofire** [comment]
Hi @rootcss,
You can maybe hack around, but it is not recommendable.
You should use different keyspaces for different applications, or different environment configuration (e.g. test / staging / production).

> I would be inclined to use one keyspace and multiple column families, primarily because the activities you are storing seem like one logical set of data.
If you use multiple keyspaces, your application would have to contain some logic to figure out which one to query. I think this type of logic is better pushed down into Cassandra (via a tenant aware index).

More about it at:
http://stackoverflow.com/a/22012348
http://stackoverflow.com/a/22390831/1172125

Regards,
Bernardo.

**Comment by bernardofire** [comment]
Duplicated of #243.

**Comment by rootcss** [comment]
Thanks @bernardofire for the detailed reply :)
