### ISSUE TITLE
TTL for rows

### ISSUE THREAD

**Issue by t33m** [cequel/cequel#339]
How use [this](http://docs.datastax.com/en/cql/3.1/cql/cql_using/use_expire_t.html) feature? It's supported by cequel?

**Comment by pezra** [comment]
@t33m, you can pass an TTL when you save a record. See https://github.com/cequel/cequel/blob/480a8477ca2587f223b9e41902a83343ceaeb2ae/spec/examples/record/persistence_spec.rb#L61 for an example.
