### ISSUE TITLE
materialized views

### ISSUE THREAD

**Issue by askuratovsky** [cequel/cequel#358]
Hello!
Is it possible to create materialized views by cequel migration?
Is it possible to read from views by cequel?
If not, do you have ideas to integrate it?
How to better use (best practice) materialized views using this gem?

**Comment by pezra** [comment]
You can create materialized views manually (https://github.com/cequel/cequel/pull/346).

I'd like to have more direct support for materialized views, though. If you are interested, submit a PR and we'll get the feature in.

**Comment by askuratovsky** [comment]
Ok, thanks for answer!
