### ISSUE TITLE
::Cassandra::Statements::Batch is breaking NewRelic

### ISSUE THREAD

**Issue by lxbrito** [cequel/cequel#360]
Cequel::Metal::NewRelicInstrumentation is passing statement_txt as nil when the statement is a  ::Cassandra::Statements::Batch and thus breaking the NewRelic Gem when it tries to truncate statement_txt.

shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/transaction_sampler.rb:155:in `truncate_message': undefined method `length' for nil:NilClass (NoMethodError)
    from shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/transaction_sampler.rb:143:in `notice_extra_data'
    from shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/transaction_sampler.rb:220:in `notice_nosql_statement'
    from shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/datastores.rb:185:in `notice_statement'
    from shared/bundle/ruby/2.3.0/gems/cequel-2.1.0/lib/cequel/metal/new_relic_instrumentation.rb:31:in `block (2 levels) in <module:NewRelicInstrumentation>'
    from shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/datastores.rb:115:in `block in wrap'
    from shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/method_tracer.rb:73:in `block in trace_execution_scoped'
    from shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
    from shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/method_tracer.rb:71:in `trace_execution_scoped'
    from shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/datastores.rb:108:in `wrap'
    from shared/bundle/ruby/2.3.0/gems/cequel-2.1.0/lib/cequel/metal/new_relic_instrumentation.rb:48:in `block in <module:NewRelicInstrumentation>'
    from shared/bundle/ruby/2.3.0/gems/cequel-2.1.0/lib/cequel/metal/batch.rb:67:in `apply'

**Comment by lxbrito** [comment]
If the fix is simply passing statement_txt as a blank string I can open a PR.

**Comment by bernardofire** [comment]
Hi @pezra, any thoughts on this?
This is the current fix we are using:
https://github.com/lxbrito/cequel/commit/b4755f445b1ab05dd1aeff69cd63b30c6708bc14

Thanks in advance.

**Comment by pezra** [comment]
Would it be better to have the statement be something like "BEGIN BATCH"? I
don't use new relic so I am not sure. Either way I would merge a PR to
resolve this issue.

**Comment by NatMorcos** [comment]
I belive this issue is closed with https://github.com/cequel/cequel/pull/361 and can be closed

**Comment by pezra** [comment]
@NatMorcos, great!
