### ISSUE TITLE
Missing version 2.1.1 on rubygems

### ISSUE THREAD

**Issue by michal-samluk** [cequel/cequel#367]
Hello, I see version 2.1.1 in the [Changelog](https://github.com/cequel/cequel/blob/master/CHANGELOG.md#211), but it is not available on ruby gems. Also, I do not see a tag for it. 
I would really appreciate if you could release it :)

**Comment by pezra** [comment]
Yep. I ran into a problem with that release. I am working to correct the issue but the short of it is: there will be no 2.1.1 release. Instead there will be a 3.0.0 release. I will update the changelog to that effect.

Real soon now. 😄 

Thanks for your interest and i apologize for the confusion.

**Comment by pezra** [comment]
3.0.0 has been released.
