### ISSUE TITLE
How can I see plain CQL query?

### ISSUE THREAD

**Issue by gruz0** [cequel/cequel#388]
Hi!

I want to see plain CQL query for my model. Is it possible?
Maybe `#to_cql` method available?

Example:
```
Blog.where(id: 123).to_cql
```

Transforms to:
```
SELECT * FROM blogs WHERE id = '123'
```

**Comment by pezra** [comment]
There really isn't an easy way at this point. The raw queries are written to the log at debug level so you could run the query and then grab the CQL out of the log.
