### ISSUE TITLE
Can't scope key column type without also scoping previous clustering column 

### ISSUE THREAD

**Issue by JasperWoo** [cequel/cequel#393]
My model
` key :membership1_id, :uuid`
`key :membership2_id, :uuid`
`key :type, :text, index: true`
`column :status, :text`

When I do `Relation.consistency(:one).where(membership1_id: membership_id, type: type)`

Cequel throws `Cequel::Record::IllegalQuery: Can't scope key column type without also scoping membership2_id`

Based on [Cassandra document](https://www.datastax.com/dev/blog/a-deep-look-to-the-cql-where-clause):

> Partition key restrictions and Secondary indices
> When Cassandra must perform a secondary index query, it will contact all the nodes to check the part of the secondary index located on each node. If all the partition key components are restricted, Cassandra will use that information to
> query only the nodes that contains the specified partition keys, which will make the query more efficient.
> 
> For secondary index queries, only = restrictions are supported on partition key columns.

Is Cequel not going to support this query which Cassandra supports? Or does cequel have a different idea as to what we should query? It doesn't really make sense for an ORM to overthrow the features of the db.

**Comment by pezra** [comment]
Due to the way Cassandra works that query cannot work against that table . This is not bug in cequel but intrinsic in Cassandra and CQL.

If you convert `type` into a column with an index the query will work as written.

Keys are hierarchical in the order defined. This means that to query on a key we must provide values for all the keys that preceded it in the table definition.

**Comment by JasperWoo** [comment]
Thanks for your reply!
"If you convert type into a column with an index the query will work as written." seems to be what I am doing here. Or do you mean something else?

**Comment by pezra** [comment]
There is a big difference between a `key` and a `column`. In order for your query to work as defined the table would need to be the following (the first word of the third row is different).
 
```
key :membership1_id, :uuid
key :membership2_id, :uuid
column :type, :text, index: true
column :status, :text
```

PS: I think it *is* a bug that `key` accepts (and ignores) the `index` option. Keys cannot be indexed.
