### ISSUE TITLE
How to create a composite partition key?

### ISSUE THREAD

**Issue by ilanusse** [cequel/cequel#402]
Hey!

I wanted to use a [composite partition key](https://docs.datastax.com/en/cql/3.3/cql/cql_using/useCompositePartitionKeyConcept.html). 

To my understanding, using Cequel's `has_many` associations results in 

I found this in `table_writer_spec.rb`:

```ruby
cequel.schema.create_table(table_name) do
  partition_key :blog_subdomain, :ascii
  partition_key :permalink, :ascii
  column :title, :text
end
```

So I went for sth that looks like this:

```ruby
class OperationByOrigin
  include Cequel::Record
  # Composite primary key should look like (user_id, profile_id, origin_date, id)
  partition_key :user_id, :int
  partition_key :profile_id, :int
  partition_key :origin_date, :date
  partition_key :id, :int
end
```

But then when I run rake I get:

```
rake cequel:migrate
rake aborted!
NoMethodError: undefined method `partition_key' for OperationByOrigin:Class
```

What is the correct syntax? Could we add it to the documentation? If the feature is missing, I'll go ahead and code it myself, I really need this.

**Comment by ilanusse** [comment]
After digging a bit deeper, it seems what I wanted was:

```ruby
key :user_id, :int, partition: true
key :profile_id, :int, partition: true
key :origin_date, :date, partition: true
key :id, :int
```

I'll keep this open for a bit to remind myself to make a PR adding this to docs

**Comment by pezra** [comment]
An update to the docs would be awesome!

**Comment by ilanusse** [comment]
https://github.com/cequel/cequel/pull/403
