### ISSUE TITLE
metal/keyspace#client doesn't actually `@return  [Cql::Client::Client]`

### ISSUE THREAD

**Issue by jtzero** [cequel/cequel#408]
`#connect` says:
https://github.com/cequel/cequel/blob/21ed966d515c265d766bcb8078b79a7a2e96146c/lib/cequel/metal/keyspace.rb#L170 however, `cluster.connect(name)` actually returns `Cassandra::Session`
https://github.com/datastax/ruby-driver/blob/master/lib/cassandra/cluster.rb#L273 

was [Cluster::Client](https://github.com/datastax/ruby-driver/blob/0a0be648115964d3cc9a45bf602286d8e5025849/lib/cassandra/cluster/client.rb) the expected return? it looks similar to Cql::Client::Client

**Comment by pezra** [comment]
I think that data type doc may have been correct in the past. I suspect that the underlying c* access library changed what class it returned at some point. We should update the docs to match the current behavior. I'd happily merge such a PR.

**Comment by ilanusse** [comment]
PR done! Would also appreciate a look at #407 please :)

**Comment by pezra** [comment]
PR merged
