### ISSUE TITLE
Use cequel with rails 7

### ISSUE THREAD

**Issue by gordienko** [cequel/cequel#430]
When I start the migration I get the error:

```
rails cequel:migrate
rails aborted!

NameError: uninitialized constant ActiveSupport::Dependencies::WatchStack

Tasks: TOP => cequel:migrate
(See full trace by running task with --trace)

```

Is there any way to fix this?

**Comment by Yamaguchi** [comment]
see https://github.com/cequel/cequel/compare/master...Yamaguchi:rails7?expand=1

This implementation works well for me.

I use the branch like:

Gemfile
```
gem 'cequel', github: "Yamaguchi/cequel", branch: "rails7"
```

**Comment by gordienko** [comment]
@Yamaguchi, Great news! I'll try it, thanks!
